version: "3.9"
services:
  nfs-server:
    image: digitbrain/bb-nfs:latest
    container_name: nfs-server
    ports:
      - "2049:2049"
    volumes:
      - "./data:/nfsshare"
    privileged: true
    environment:
      - "SHARED_DIRECTORY=/nfsshare"
    volumes:
      - ./data:/nfsshare
    restart: always